server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: horaExtra-service
          uri: lb://horaExtra-service
          predicates:
            - Path=/horaExtra/**
        
        - id: justificativo-service
          uri: lb://justificativo-service
          predicates:
            - Path=/justificativo/**
        
        - id: calcular-service
          uri: lb://calcular-service
          predicates:
            - Path=/calcular/**
        
        - id: reporte-service
          uri: lb://reporte-service
          predicates:
            - Path=/reporte/**
        
        - id: importar-service
          uri: lb://importar-service
          predicates:
            - Path=/importar/**, /horario/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
            - GET
            - POST