server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: pet-service
          uri: lb://pet-service
          predicates:
            - Path=/pet/**
        
        - id: horaExtra-service
          uri: lb://horaExtra-service
          predicates:
            - Path=/horaExtra/**